---
title: "Annotated Bibliography"
bibliography: references.bib
csl: chicago-syllabus.csl
suppress-bibliography: true
link-citations: false
citations-hover: false
---

# Annual Review Article

@huangInfectiousDiseaseModeling2025

# References

@haoReconstructionFullTransmission2020

Hao et al. communicates their study of the transmission of the virus in Wuhan. They analyzed the effect of intervention and carefully modeled how different stages of the virus contributed to the spread of the disease, noting "covertness". It further discusses how there is another variation of the SEIP (Susceptible, Exposed, Infectious, and Recovered) model to predict the transmission of COVID-19, including additional classifications: unascertained cases and presymptomatic infectiousness. This is an extension of the "covertness" described as the virus could be spread even without symptoms. The article proves it reliability with its sections promoting reproducibility, such as code and data availability, and there are no stated competing interests from the authors. What would be helpful to know would be more about stochastic simulations and the equations following listed as equivalent to their dynamics. Another piece to get more information on is credible intervals and how they compare and contrast to confidence intervals.

@harkoExactAnalyticalSolutions2014
    
Harko et al. reports of the necessity of births and deaths into the previously discussed disease transmission simulation model. Once again, there is another model of SEIP as discussed by Huang et al. with slight variation. Instead, the produced model is known as SIP, removing the exposed classification, and includes equal birth and death rates as an important addition. Several differential equations construct the mathematical bones for modeling transmission rates and movement between the three stages of disease. One detail which makes me question the potential reliability of the article is the mention of commentators and anonymous suggestions that led to the improvement of the manuscript in the Acknowledgements section. It is unclear whether the anonymity is due to the author's lack of knowledge on who left the comments or the wish for the individual's identities of those who left the comments to remain anonymous. It is much harder than the article written by Hao et al. to know if there are competing interests with either the journal or the authors that would prove as motive for the creation of the article. The words "exact" and "easy" in various shapes and forms leave the impression that the article is doing the critical thinking for the readers and they have predetermined that their method is above all. In order to understand the article better, I would like to know more about Abel equations and the mathematical or greater field context in which "exact" is allowed. "True" is a term that is used when describing certain ways to calculate confidence intervals, so there could be a potential similar use with "exact" that is not as apparent as the article may present.